# Generated by Django 2.0.1 on 2018-01-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('first', models.CharField(blank=True, max_length=25)),
                ('last', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
