# Generated by Django 2.0.3 on 2018-04-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TaskApp', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('redirect_uris', models.CharField(max_length=100)),
                ('client_type', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('authorization_grant_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
